title: Laravel Edgelink Docs
description: Documentation for the otghcloud/laravel-edgelink package.
theme: jekyll-theme-cayman
markdown: kramdown
repository_url: https://github.com/otghcloud/laravel-edgelink

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: docs
